# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            Jiang's Blog
tagline:          'blog'
description:      'Jiang Wang blog'
url:              http://wangjiangb.github.io
baseurl:
commentsystem:    google
disqus:           wangjiangb

author:
  name:           Jiang Wang
  url:            http://users.eecs.northwestern.edu/~jwa368/

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

social:
  - icon:         twitter
    url:          https://twitter.com/iancamporez
    desc:         Follow me on twitter

  - icon:         github
    url:          https://github.com/camporez
    desc:         Fork me on github

  - icon:         googleplus-alt
    url:          https://google.com/+IanCamporezBrunelli
    desc:         Add me on google+

  - icon:         feed
    url:          http://camporez.com/atom.xml
    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:         Jiang Wang
  url:             http://users.eecs.northwestern.edu/~jwa368/
  type_title:     ''
  type_url:       ''

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
